#!/bin/bash

echo "Installing flowR addin..."

Rscript -e "install.packages('remotes', repos = 'https://cloud.r-project.org')"

Rscript -e "if (Sys.getenv('GITHUB_ACCESS_TOKEN') != '') Sys.setenv(GITHUB_PAT = Sys.getenv('GITHUB_ACCESS_TOKEN')); remotes::install_github('flowr-analysis/rstudio-addin-flowr@v0.1.2')"

echo -e '\nsetwd("/home/jovyan/rs6un_src/Code and simulations results second revision - March 2021/Simulation Study I/AR")' >> /home/jovyan/.Rprofile
